routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

Route::resource('assets', 'AssetController');
Route::resource('categories', 'CategoryController');
Route::resource('transactions', 'TransactionController');

app/Http/Controllers/TransactionController.php
<?php

namespace App\Http\Controllers;

use App\Transaction;
use Illuminate\Http\Request;

use Auth;
use Str;
use Session;
use App\Asset;
use App\Status;
use App\User;
use App\Category;

class TransactionController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        // echo "welcome to transactions";

        if (Auth::user()->role_id == 1) {
        $transactions = Transaction::all();
        $pending_transactions = Transaction::all()->where('status_id', 3);
        $approved_transactions = Transaction::all()->where('status_id', 4);
        $completed_transactions = Transaction::all()->whereIn('status_id', [5,6]);
        $cancelled_transactions = Transaction::all()->where('status_id', 7);
        
        
        // admin can see all transactions
        }
        else {
        $transactions = Transaction::all();
        $pending_transactions = Transaction::all()->where('status_id', 3)->where('user_id', Auth::user()->id);
        $approved_transactions = Transaction::all()->where('status_id', 4)->where('user_id', Auth::user()->id);
        $completed_transactions = Transaction::all()->whereIn('status_id', [5,6])->where('user_id', Auth::user()->id);
        $cancelled_transactions = Transaction::all()->where('status_id', 7)->where('user_id', Auth::user()->id);
        // only transaction where the login user_id only sees
        // $transactions = Transaction::where('user_id', Auth::user()->id)->get();
        }

        $statuses = Status::all();
        $categories = Category::all();
        $assets = Asset::all();

        // dd($transactions);
        return view('transactions.index')
            ->with('transactions', $transactions)
            ->with('categories', $categories)
            ->with('statuses', $statuses)
            ->with('assets', $assets)
            ->with('pending_transactions', $pending_transactions)
            ->with('approved_transactions', $approved_transactions)
            ->with('completed_transactions', $completed_transactions)
            ->with('cancelled_transactions', $cancelled_transactions);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request, Category $category)
    {
        $assets=Asset::all();
        // echo "from transaction -store";
        $transaction = new Transaction;

        $transaction_number = Auth::user()->id . Str::random(5) . time();


        $user_id = Auth::user()->id;
        // status_id set to pending
        $status_id = 3;

        $transaction->borrow_date = $request->input('borrow');

        $transaction->return_date = $request->input('return');

        $transaction->asset_id = $request->input('asset_id');

        $transaction->transaction_number = $transaction_number;
        $transaction->user_id = $user_id;
        $transaction->status_id = $status_id;
        $transaction->save();

        // $request->validate([
        //     'id' => 'required',
        //     'quantity' => 'default(1)'
        // ]);

        // $asset_quantity = 5;
        // $id = $request->input('category_id');

        // $request->session()->put("trans.$id", $asset_quantity);

        // $trans_ids = array_keys(Session::get('trans'));

        // $trans = Transaction::find($trans_ids);
        // dd($trans);


        // pivot table
        // foreach($assets as $asset)
        // {
        // $transaction->assets()->attach($asset->id, [
        //     'borrow_date' => $request->input('borrow'),
        //     'return_date' => $request->input('return')
        // ]);
        // }

        // dd($transaction->assets);
        return redirect(route('transactions.show',['transaction'=> $transaction->id]));
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Transaction  $transaction
     * @return \Illuminate\Http\Response
     */
    public function show(Transaction $transaction)
    {
        // echo "hello from transaction store";
        // dd($transaction);
        return view('transactions.show')->with('transaction', $transaction);
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Transaction  $transaction
     * @return \Illuminate\Http\Response
     */
    public function edit(Transaction $transaction)
    {
        
    }
 
    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Transaction  $transaction
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Transaction $transaction)
    {
        // echo "hello from transaction update";
        $transaction->status_id = $request->input('status_id');
        $transaction->save();

        return redirect()->back();
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Transaction  $transaction
     * @return \Illuminate\Http\Response
     */
    public function destroy(Transaction $transaction, Request $request)
    {
        // echo "string";
        $transaction->status_id = $request->input('status_id');
        $transaction->save();
        return redirect()->back();
    }
}

resources/views/transactions/index.blade.php
@extends('layouts.app')


@section('content')
{{-- for pending --}}
{{-- {{dd($pending_transactions)}} --}}
{{--             @foreach($transactions as $trans)
            @foreach($trans->assets as $ass)
            {{dd($ass)}}
            @endforeach
            @endforeach --}}
            <div class="contrainer">

              <h3 class="text-center">Transaction Pending Approval</h3>
              <div class="row">
                <div class="col-12 col-md-11 mx-auto">

                  <table class="table table-dark">
                    <thead>
                      <tr>
                        <th scope="col">User</th>
                        <th scope="col">Category Line</th>
                        <th scope="col">Borrow Date</th>
                        <th scope="col">Return Date</th>
                        <th scope="col">Status</th>
                        <th scope="col">Actions</th>
                      </tr>
                    </thead>
                    <tbody>

                      @foreach($pending_transactions as $tran)
                      {{-- @foreach($trans->assets as $ass) --}}
                      {{-- {{dd($tran)}} --}}
                      {{-- {{dd($tran->assets)}} --}}
                      <tr class="table-active">
                        <td scope="row">{{$tran->user->name}}</td>
                        {{-- {{dd($pending_transactions)}} --}}
                        {{-- @foreach($tran as $ass) --}}
                        {{-- {{dd($ass)}} --}}
                        {{-- @endforeach --}}
                        {{-- {{$tran->assets->name}} --}}
                        {{-- <td>{{$tran->transaction_number}}</td> --}}
                        <td>{{$tran->asset->category->name}}</td>
                        {{-- @endforeach --}}
                        <td>{{$tran->borrow_date}}</td>
                        <td>
                          {{$tran->return_date}}
                        </td>
                        {{-- @endforeach --}}

                        {{-- <td>{{$trans->category->description}}</td> --}}

                        {{-- @endforeach --}}
                        <td>{{$tran->status->name}}</td>
                        <td>

                          @can('isAdmin')
                          <form action="{{ route('transactions.update',['transaction' => $tran->id])}}" method="POST">

                            @csrf
                            @method('PUT')
                            <input type="hidden" name="status_id" value="4">
                            <button class="btn btn-success approveBtn form-control">Approve</button>
                          </form>

                          <form action="{{ route('transactions.destroy',['transaction' => $tran->id])}}" method="POST">
                            @csrf
                            @method('DELETE')
                            <input type="hidden" name="status_id" value="6">
                            <button class="btn btn-danger form-control">Reject</button>
                          </form>
                          @endcan

                          @cannot('isAdmin')
                          <form action="{{ route('transactions.destroy',['transaction' => $tran->id])}}" method="POST">
                            @csrf
                            @method('DELETE')
                            <input type="hidden" name="status_id" value="7">
                            <button class="btn btn-warning form-control">Cancel</button>
                          </form>
                          @endcannot

                        </td>
                      </tr>
                      {{-- @endforeach --}}
                      @endforeach

                      {{-- {{dd(Session::all("fdsafdsa.$tran", '$tran->category.id'))}} --}}

                    </tbody>
                  </table> 

                </div> {{-- end of col --}}
              </div> {{-- end of row --}}
            </div>{{-- end of container --}}

            {{-- for approved --}}
            <hr>

            <div class="contrainer">
              <h3 class="text-center">Approved Transactions</h3>
              <div class="row">
                <div class="col-12 col-md-11 mx-auto">

                  <table class="table table-dark">
                    <thead>
                      <tr>
                        <th scope="col">User</th>
                        <th scope="col">Transaction Number</th>
                        <th scope="col">Asset</th>
                        <th scope="col">Borrow Date</th>
                        <th scope="col">Return Date</th>
                        <th scope="col">Approve On</th>
                        <th scope="col">Actions</th>
                      </tr>
                    </thead>
                    <tbody>

                      @foreach($approved_transactions as $tran)
                      <tr class="table-active">
                        <th scope="row">{{$tran->user->name}}</th>
                        <td>{{$tran->transaction_number}}</td>
                        <td>
                          {{$tran->asset->name}}
                        </td>
                        <td>
                          {{$tran->borrow_date}}
                        </td>
                        <td>{{$tran->return_date}}</td>
                        <td>{{$tran->updated_at}}</td>
                        <td>
                          <form action="{{ route('transactions.update',['transaction' => $tran->id])}}" method="POST">
                            @csrf
                            @method('PUT')
                            <input type="hidden" name="status_id" value="5">
                            <button class="btn btn-success approveBtn form-control">Tag as Returned</button>
                          </form>
                        </td>
                      </tr>
                      {{-- @endif --}}
                      @endforeach
                    </tbody>
                  </table> 

                </div> {{-- end of col --}}
              </div> {{-- end of row --}}
            </div>{{-- end of container --}}

            <hr>
            {{-- for completed --}}

            <div class="contrainer">
              <h3 class="text-center">Completed Transactions</h3>
              <div class="row">
                <div class="col-12 col-md-11 mx-auto">

                  <table class="table table-dark">
                    <thead>
                      <tr>
                        <th scope="col">User</th>
                        <th scope="col">Transaction Number</th>
                        <th scope="col">Asset</th>
                        <th scope="col">Borrow Date</th>
                        <th scope="col">Return Date</th>
                        <th scope="col">Status</th>
                        <th scope="col">Completed On</th>
                      </tr>
                    </thead>
                    <tbody>

                      @foreach($completed_transactions as $tran)
                      <tr class="table-active">
                        <th scope="row">{{$tran->user->name}}</th>
                        <td>{{$tran->transaction_number}}</td>
                        <td>
                          {{$tran->asset->name}}
                        </td>
                        <td>
                          {{$tran->borrow_date}}
                        </td>
                        <td>{{$tran->return_date}}</td>
                        <td>{{$tran->status->name}}</td>
                        <td>{{$tran->updated_at}}</td>
                      </tr>
                      {{-- @endif --}}
                      @endforeach
                    </tbody>
                  </table> 

                </div> {{-- end of col --}}
              </div> {{-- end of row --}}
            </div>{{-- end of container --}}

            <hr>
            {{-- for completed --}}

            <div class="contrainer">
              <h3 class="text-center">Cancelled Transactions</h3>
              <div class="row">
                <div class="col-12 col-md-11 mx-auto">

                  <table class="table table-dark">
                    <thead>
                      <tr>
                        <th scope="col">User</th>
                        <th scope="col">Transaction Number</th>
                        <th scope="col">Asset</th>
                        <th scope="col">Borrow Date</th>
                        <th scope="col">Return Date</th>
                        <th scope="col">Status</th>
                        <th scope="col">Cancelled On</th>
                      </tr>
                    </thead>
                    <tbody>

                      @foreach($cancelled_transactions as $tran)
                      <tr class="table-active">
                        <th scope="row">{{$tran->user->name}}</th>
                        <td>{{$tran->transaction_number}}</td>
                        <td>
                          {{$tran->asset->name}}
                        </td>
                        <td>
                          {{$tran->borrow_date}}
                        </td>
                        <td>{{$tran->return_date}}</td>
                        <td>{{$tran->status->name}}</td>
                        <td>{{$tran->updated_at}}</td>
                      </tr>
                      {{-- @endif --}}
                      @endforeach
                    </tbody>
                  </table> 

                </div> {{-- end of col --}}
              </div> {{-- end of row --}}
            </div>{{-- end of container --}}

            @endsection


{{-- <tr>
            <th scope="row">Default</th>
            <td>Column content</td>
            <td>Column content</td>
            <td>Column content</td>
          </tr>
          <tr class="table-primary">
            <th scope="row">Primary</th>
            <td>Column content</td>
            <td>Column content</td>
            <td>Column content</td>
          </tr>
          <tr class="table-secondary">
            <th scope="row">Secondary</th>
            <td>Column content</td>
            <td>Column content</td>
            <td>Column content</td>
          </tr>
          <tr class="table-success">
            <th scope="row">Success</th>
            <td>Column content</td>
            <td>Column content</td>
            <td>Column content</td>
          </tr>
          <tr class="table-danger">
            <th scope="row">Danger</th>
            <td>Column content</td>
            <td>Column content</td>
            <td>Column content</td>
          </tr>
          <tr class="table-warning">
            <th scope="row">Warning</th>
            <td>Column content</td>
            <td>Column content</td>
            <td>Column content</td>
          </tr>
          <tr class="table-info">
            <th scope="row">Info</th>
            <td>Column content</td>
            <td>Column content</td>
            <td>Column content</td>
          </tr>
          <tr class="table-light">
            <th scope="row">Light</th>
            <td>Column content</td>
            <td>Column content</td>
            <td>Column content</td>
          </tr>
          <tr class="table-dark">
            <th scope="row">Dark</th>
            <td>Column content</td>
            <td>Column content</td>
            <td>Column content</td>
          </tr> --}}

resources/views/transactions/show.blade.php
@extends('layouts.app')

@section('content')
{{-- {{$transaction}} --}}
{{-- {{dd(Session::get('transaction'))}} --}}
<div class="container">
	<div class="row">
		<div class="col-12 col-md-8 mx-auto">
			<h3 class="text-center">Transaction Details</h3>
			<hr>
		</div> {{-- end of col --}}		
	</div> {{-- end of row --}}

	<div class="row">
		<div class="col-12 col-md-8 mx-auto">
			<div class="table-reponsive">
				<table class="table table-sm table-borderless">

					<tbody>
						<tr>
							<td>Customer Name:</td>
							<td> <strong>{{$transaction->user->name}}</strong> </td>

						</tr>

						<tr>
							<td>Transaction Number:</td>
							<td><strong> {{strtoupper($transaction->transaction_number)}} </strong></td>

						</tr>

						<tr>
							<td>Status:</td>
							<td>{{$transaction->status->name}}</td>

						</tr>

						<tr>
							<td>Request Date:</td>
							<td>{{$transaction->created_at->format('d-F-Y m:i:s')}}</td>

						</tr>
						{{-- remove pivot --}}
					{{-- @foreach($transaction->assets as $transaction_asset) --}}
					{{-- @endforeach --}}
						<tr>
							<td>Borrow Date:</td>
							<td>{{$transaction->borrow_date}}</td>

						</tr>

						<tr>
							<td>Return Date:</td>
							<td>{{$transaction->return_date}}</td>

						</tr>

					</tbody>

				</table>


			</div>
		</div> {{-- end of 2nd col --}}
	</div> {{-- end of 2nd row --}}
</div> {{-- end of containter --}}

@endsection