routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

Route::resource('assets', 'AssetController');
Route::resource('categories', 'CategoryController');
Route::resource('transactions', 'TransactionController');

app/Category.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;

class Category extends Model
{
	// protected $fillable = [
 //        'id', 'name',
 //    ];

	use SoftDeletes;
    public function assets() {
    	return $this->hasMany('App\Asset');
    }


    // public function transactions()
    // {
    // 	// return $this->hasMany('App\Transaction', 'transaction_asset');
    // 				// ->withPivot('borrow_date','return_date')
    //     //             ->withTimestamps();
        
    // }

}

app/Http/Controllers/CategoryController.php
<?php

namespace App\Http\Controllers;

use App\Asset;
use App\Category;
use App\Transaction;
use App\Status;
use Illuminate\Http\Request;
use Str;

class CategoryController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $categories = Category::all();
        $assets = Asset::all();
        $transactions = Transaction::all();
        return view('categories.index')
            ->with('categories', $categories)
            ->with('assets', $assets)
            ->with('transactions', $transactions);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        // echo "hi from category - store";
        $request->validate ([
            'category_name' => 'required|unique:categories,name',
            'category_image' => 'required|image|max:20000',
            'category_desc' => 'required|string'
        ]);

        $file = $request->file('category_image');

        $file_name = pathinfo($file->getClientOriginalName(),PATHINFO_FILENAME);
     
        $file_extension = $file->extension();

        $random_chars = Str::random(5);

        $new_filename = date('Y-m-d-H-i-s') . "_" . $random_chars . "_" . $file_name . "." . $file_extension;

        $filepath = $file->storeAs('images', $new_filename, 'public');


        $name = $request->input('category_name');
        $description = $request->input('category_desc');
        $image = $filepath;

        $category = new Category;
        $category->name = $name;
        $category->description = $description;
        $category->image = $image;
        // $category->quantity = 10;
        $category->save();

        $request->session()->flash('category_message','category successfully added');
        return redirect(route('assets.create'));
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Category  $category
     * @return \Illuminate\Http\Response
     */
    public function show(Category $category)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Category  $category
     * @return \Illuminate\Http\Response
     */
    public function edit(Category $category)
    {
        // echo "hi from category edit";
        $assets = Asset::all();
        return view('categories.edit')
            ->with('assets', $assets)
            ->with('category', $category);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Category  $category
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Category $category)
    {
        // dd($request->input('category_name'));
        // echo "hi from categories update";
        $request->validate ([
            'category_name' => 'required|unique:categories,name',
            'category_description' => 'required|string'
        ]);

        if(!$request->hasFile('category_image') && 
            $category->name == $request->input('category_name') &&
            $category->description == $request->input('category_description')) 
        {
            $request->session()->flash('update_failed', 'No changes made | Something went wrong');
        }


        else {
            if($request->hasFile('category_image'))
            {
                $request->validate([
                    'category_image' => 'required|image|max:20000',
                ]);

                $file =$request->file('category_image');

                $file_name = pathinfo($file->getClientOriginalName(), PATHINFO_FILENAME);

                $file_extension = $file->extension();

                $random_chars = Str::random(5);

                $new_filename = date('Y-m-d-H-i-s') . "_" . $random_chars . "_" . $file_name . "." . $file_extension;

                $filepath = $file->storeAs('images', $new_filename,'public');

                $category->image = $filepath;

            }

            $category->name = $request->input('category_name');
            $category->description = $request->input('category_description');
            // $category->quantity = 10;
            $category->save();

            $request->session()->flash('update_success', 'Category successfully updated');

        }

        return redirect (route ('categories.edit',['category'=> $category->id]));
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Category  $category
     * @return \Illuminate\Http\Response
     */
    public function destroy(Category $category)
    {
        // echo "from category destroy";
        $category->delete();

        return redirect(route('categories.index'))->with('destroy_message','Category has been deleted');
    }
}

resources/views/categories/edit.blade.php
@extends('layouts.app')


@section('content')

<div class="container">
	<div class="row">
		<div class="col-12 cold-md-8 mx-auto">
			<h3 class="text-center">
				Edit Category
			</h3>
			<hr>

			@if(Session::has('update_failed'))
			<div class="alert alert-warning">
				{{ Session::get ('update_failed') }}
			</div>
			@elseif(Session::has('update_success'))
			<div class="alert alert-success">
				{{ Session::get ('update_success') }}
			</div>
			@endif

			<form action="{{ route ('categories.update', ['category' => $category->id]) }}" method="POST" enctype="multipart/form-data">
				
				@csrf
				@method('PUT')

				{{-- name input --}}
				<div class="form-group">
					<label for="category_name">
					Category name:
					</label>
					<input id="category_name" type="text" name="category_name" class="form-control" value="{{$category->name}}">					

				</div> {{-- end of name input --}}

				@if($errors->has('category_name'))
				<div class="alert alert-danger">
					<small class="mb-0">Category name Required</small>
				</div>
				@endif

				<div class="form-group">
					<label for="category_image">Category image:</label>
					<input id="category_image" type="file" name="category_image" class="form-control-file">
				</div> {{-- end of category images --}}

				@if($errors->has('category_image'))
				<div class="alert alert-danger">
					<small class="mb-0">Category image Required Check if images is not greater that 2.00mb</small>
				</div>
				@endif

				<div class="form-group">
					<label for="category_description">Product Description</label>
					<textarea 
					id="category_description" 
					class="form-control" 
					name="category_description" 
					cols="30" 
					rows="10">{{ $category->description }}</textarea>
				</div> {{-- end of category description --}}

				@if($errors->has('category_description'))
				<div class="alert alert-danger">
					<small class="mb-0">Category description Required</small>
				</div>
				@endif

				<button class="btn btn-primary btn-block">Edit Category</button>






			</form> {{-- end of form --}}


			

		</div> {{-- end of column --}}


	</div> {{-- end of row --}}


</div> {{-- end of container --}}

@endsection

resources/views/categories/index.blade.php
@extends('layouts.app')


@section('content')
{{-- {{dd($assets)}} --}}
<div class="container">
	<div class="row">
		<div class="col-12">
			<div class="jumbotron">
				<h1 class="text-center">
					Choose your equipment!!!
				</h1>

			</div> {{-- end of jumbotron --}}

		</div>{{-- end of column --}}	

	</div> {{-- end of row upper--}}

	@if(Session::has('destroy_message'))
	<div class="alert alert-danger">
		{{ Session::get ('destroy_message') }}
	</div>
	@endif

	<div class="row">
		<div class="col-12 col-md-12 mx-auto">
			<div class="row">
				@foreach($categories as $category)
				<div class="col-12 col-md-6 my-2">
					{{-- start of card --}}
					<div class="card">
						<img src="{{ url('/public/' . $category->image) }}" 
						class="card-img-top card-image mx-auto mt-1 img-fluid img-thumbnail" 
						alt="Responsive image"
						>
						<div class="card-body">
							<h4 class="card-title">
								{{$category->name}}
							</h4>
							<p class="card-text">
								{{$category->description}}
							</p>		
						</div> {{-- end of card-body --}}			
						<div class="card-foot">

							<div class="accordion" id="accordionExample">
								<div class="card">
									<div class="card-header" id="headingOne">
										<h2 class="mb-0">
											<button class="btn btn-link" 
											type="button" 
											data-toggle="collapse" 
											data-target="#category-{{$category->id}}" 
											aria-expanded="true" 
											aria-controls="collapseOne">
											Asset Unit
										</button>
									</h2>
								</div>


								<div id="category-{{$category->id}}" class="collapse" aria-labelledby="headingOne" data-parent="#accordionExample">
									<div class="card-body">
										<div class="accordion container" id="accordionExample1">
											<div class="container">
												<div class="row">
													<div class="col-12">
														<div class="row">

															@foreach($assets as $asset)
															@if($category->id == $asset->category_id)
															<div class="col-12 my-1">
																<div class="card">
																	<div class="card-header" id="headingOne1">
																		<h2 class="mb-0">
																			<button 
																			class="btn btn-link" 
																			type="button" 
																			data-toggle="collapse" 
																			data-target="#asset-{{ $asset->id }}"
																			aria-expanded="true" 
																			aria-controls="collapseOne">
																			<img src="{{ url('/public/' . $asset->image) }}" 
																			class="img-fluid img-thumbnail" 
																			alt="Responsive image">

																			{{ $asset->name }}
																		</button>
																	</h2>
																</div>
																<div id="asset-{{ $asset->id }}" 
																	class="collapse" 
																	aria-labelledby="headingOne1" 
																	data-parent="#accordionExample1">
																	<div class="card-body">
																		@can('isAdmin')
																		<a href="{{ route ('assets.edit', ['asset' => $asset->id] ) }}" class="btn btn-success my-1 btn-sm rounded btn-block">Edit Asset</a>

																		<form action="{{ route ('assets.destroy', ['asset' => $asset->id]) }}" method="POST">
																			@csrf
																			@method('DELETE')
																			<button class="btn btn-danger my-1 btn-sm rounded btn-block">Delete Asset</button>
																		</form>
																		@endcan

																		<form action="{{route('transactions.store')}}" method="POST">
																			{{-- goes to store- its the confirmation --}}
																			@csrf
																			<input type="hidden" name="asset_id" value="{{$asset->id}}">

																			<label for="borrow">Borrow date:</label>
																			<input type="date" name="borrow" id="borrow" class="form-control">
																			<label for="return">Return date:</label>
																			<input type="date" name="return" id="return" class="form-control">


																			<button 
																			{{-- @cannot('isLogged') --}}
																			{{-- type="button" data-toggle="modal"  --}}
																			{{-- data-target="#authentication-modal"	 --}}
																			{{-- default is submit --}}
																			{{-- @endcannot --}}
																			class="btn btn-info btn-sm btn-block rounded my1">Request</button>
																		</form>
																	</div>
																</div>
															</div>
														</div>
														@endif
														@endforeach

													</div>
												</div>
											</div>
										</div>

									</div>
								</div>
							</div>
						</div>




					</div>

					{{-- edit category button --}}
					@can('isAdmin')
					<a href="{{ route ('categories.edit', ['category' => $category->id] ) }}" class="btn btn-warning btn-block my-1 rounded">Edit Category</a>

					{{-- delete category button --}}
					<form action="{{ route ('categories.destroy', ['category' => $category->id]) }}" method="POST">
						@csrf
						@method('DELETE')

						<button class="btn btn-danger btn-block rounded">Delete Category</button>
					</form>
					@endcan					

				</div> {{-- end of card-foot --}}

			</div> {{-- end of card --}}
		</div>
		@endforeach

	</div>

</div> {{-- end of column --}}		

</div> {{-- end of lower row --}}

</div> {{-- end of caontainer --}}


@endsection