routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

Route::resource('assets', 'AssetController');
Route::resource('categories', 'CategoryController');
Route::resource('transactions', 'TransactionController');

app/Asset.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;

class Asset extends Model
{
	use SoftDeletes;
	public function category() 
    {
    	return $this->belongsTo('App\Category');
    }

    public function transactions()
    {
    	return $this->hasMany('App\Transaction');
    		// ->withPivot('borrow_date','return_date')
      //       ->withTimestamps();
        // return $this->belongsToMany('App\Transaction');
    }
}

app/Http/Controllers/AssetController.php
<?php

namespace App\Http\Controllers;

use App\Status;
use App\Asset;
use App\Category;
use Illuminate\Http\Request;
use Str;

class AssetController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        // echo "hi from asset - index";
        $assets = Asset::all();
        // dd($assets);
        return view('assets.index')->with('assets', $assets);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create(Asset $asset)
    {
        // echo 'hi from assets - create';
        $categories = Category::all();
        return view('assets.create')->with('categories', $categories);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request, Asset $asset)
    {

        // echo 'hello fron assets store';
        $request->validate([
            'name'=>'required|string',
            'serial_number'=>'required|string',
            'description'=>'required|string',
            'image'=>'required|image|max:20000',
            'quantity'=>'required|numeric'
        ]);

        $file = $request->file('image');

        $file_name = pathinfo($file->getClientOriginalName(),PATHINFO_FILENAME);
        // dd($file);

        $file_extension = $file->extension();

        $random_chars = Str::random(5);

        $new_filename = date('Y-m-d-H-i-s') . "_" . $random_chars . "_" . $file_name . "." . $file_extension;

        $filepath = $file->storeAs('images', $new_filename,'public');

        $name = $request->input('name');
        $serial_number = $request->input('serial_number');
        $description = $request->input('description');
        $image = $filepath;
        $quantity = $request->input('quantity');
        $category_id = $request->input('category');
        // dd($image);

        $asset = new Asset;
        $asset->name = $name;
        $asset->serial_number = $serial_number;
        $asset->description = $description;
        $asset->image = $image;
        $asset->quantity = $quantity;
        $asset->category_id = $category_id;
        $asset->save();

        return redirect(route('assets.show',['asset'=>$asset->id]));
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Asset  $asset
     * @return \Illuminate\Http\Response
     */
    public function show(Asset $asset)
    {
        return view('assets.show')->with('asset', $asset);
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Asset  $asset
     * @return \Illuminate\Http\Response
     */
    public function edit(Asset $asset)
    {
    // echo "hi from assets-edit";
        $categories = Category::all();
        return view('assets.edit')
        ->with('asset',$asset)
        ->with('categories', $categories);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Asset  $asset
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Asset $asset)
    {
        // echo "hi from asets-update";
        $request->validate([
            'name'=>'required|string',
            'serial_number'=>'required|string',
            'description'=>'required|string',
            // 'image'=>'required|image|max:20000',
            'quantity'=>'required|numeric'
        ]);

        if(!$request->hasFile('image') && 
            $asset->name == $request->input('name') &&
            $asset->description == $request->input('description') &&
            $asset->quantity == $request->input('quantity') &&
            $asset->category_id == $request->input('category') ) 
        {
            $request->session()->flash('update_failed', 'No changes made | Something went wrong');
        }

        else {

            if($request->hasFile('image'))
            {
                $request->validate([
                    'image' => 'required|image|max:20000'
                ]);

                $file = $request->file('image');

                $file_name = pathinfo($file->getClientOriginalName(),PATHINFO_FILENAME);

                $file_extension = $file->extension();

                $random_chars = Str::random(5);

                $new_filename = date('Y-m-d-H-i-s') . "_" . $random_chars . "_" . $file_name . "." . $file_extension;

                $filepath = $file->storeAs('images', $new_filename,'public');

                $asset->image = $filepath;
            }

            $asset->name = $request->input('name');
            $asset->serial_number = $request->input('serial_number');
            $asset->description = $request->input('description');
            $asset->quantity = $request->input('quantity');
            $asset->category_id = $request->input('category');

            $asset->save();

            $request->session()->flash('update_success', 'Asset succesfully Updated');

        }
        return redirect(route('assets.edit',['asset'=>$asset->id]));
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Asset  $asset
     * @return \Illuminate\Http\Response
     */
    public function destroy(Asset $asset)
    {
        // echo "bye bye bye";
        $asset->delete();

        return redirect(route('categories.index'))->with('destroy_message','Asset has been deleted');
    }
}

resources/views/assets/create.blade.php
@extends('layouts.app')


@section('content')

<div class="container">
	<div class="row">
		<div class="col-12 col-md-6 mx-auto">

			<h3 class="text-center">
				Add Asset
			</h3>		
			<hr>

			<form action="{{ route('assets.store') }}" method="POST" enctype="multipart/form-data">
				@csrf

				<div class="form-group">
					<label class="form-control" for="name">
						Asset name:
					</label>
					<input id="name" type="text" name="name" class="form-control">

				</div> <!-- end of name input -->

				@if($errors->has('name'))
				<div class="alert alert-danger">
					<small class="mb-0">Product name Required</small>
				</div>
				@endif

				<div class="form-group">
					<label for="serial_number" class="form-control">
						Serial number:
					</label>
					<input type="text" name="serial_number" id="serial_number" class="form-control">

				</div> <!-- end of serial_number -->

				@if($errors->has('serial_number'))
				<div class="alert alert-danger">
					<small class="mb-0">Serial number Required</small>
				</div>
				@endif

				<div class="form-group">
					<label for="category">
						Asset category
					</label>

					<select class="form-control" id="category" name="category">
						@foreach($categories as $category)
						<option value="{{ $category->id }}">
							{{ $category->name }}
						</option>
						@endforeach
						
					</select>

				</div> <!-- end of category -->

				@if($errors->has('category'))
				<div class="alert alert-danger">
					<small class="mb-0">Product category Required</small>
				</div>
				@endif

				<div class="form-group">
					<label for="quantity">
						Quantity:
					</label>
					<input type="number" name="quantity" id="quantity" class="form-control" min="1">

				</div> {{-- end of quantity input --}}

				@if($errors->has('quantity'))
				<div class="alert alert-danger">
					<small class="mb-0">Quantity is Required</small>

				</div> 
				@endif

				<div class="form-group">
					<label for="image">
						Product image:
					</label>
					<input type="file" name="image" id="image" class="form-control">		

				</div> <!-- end of image input -->

				@if($errors->has('image'))
				<div class="alert alert-danger">
					<small class="mb-0">Product image Required Check if images is not greater that 2.00mb</small>
				</div>
				@endif

				<div class="form-group">
					<label for="description">
						Product description
					</label>
					<textarea
					id="description"
					class="form-control"
					name="description"
					cols="30"
					rows = "10">
				</textarea>

			</div> <!-- end of description input -->

			@if($errors->has('description'))
			<div class="alert alert-danger">
				<small class="mb-0">Product description Required</small>
			</div>
			@endif

			<button class="btn btn-primary btn-block">
				Add asset
			</button>

		</form>	<!-- end of form -->

	</div> <!-- end of column add asset -->

	<div class="col-12 col-md-6 mx-auto">

		@if (Session::has('category_message'))
		<div class="alert alert-success">
			{{Session::get ('category_message') }}
		</div>
		@endif

		@if($errors->has('add_category'))
		<div class="alert alert-secondary">
			Category not added
		</div>
		@endif

		<h3 class="text-center">
			Add category
		</h3>
		<hr>

		<form action="{{ route('categories.store') }}" method="POST" enctype="multipart/form-data">
			@csrf

			<div class="form-group">
				<label class="form-control" for="category_name">
					Category name:
				</label>
				<input type="text" name="category_name" id="category_name" class="form-control">
			</div>

			@if($errors->has('category_name'))
			<div class="alert alert-danger">
				<small class="mb-0">Category name Required</small>
			</div>
			@endif

			<div class="form-group">
				<label class="form-control" for="category_image">
					Category image:
				</label>
				<input type="file" name="category_image" id="category_image" class="form-control">
			</div>

			@if($errors->has('image'))
			<div class="alert alert-danger">
				<small class="mb-0">Product image Required Check if images is not greater that 2.00mb</small>
			</div>
			@endif

{{-- 				<div class="form-group">
					<label class="form-control" for="category_name">
						Category quantity:
					</label>
					<input type="text" name="category_name" id="category_name" class="form-control">
				</div> --}}

				<div class="form-group">
					<label for="category_desc">
						Category description:
					</label>
					<textarea
					id="category_desc"
					class="form-control"
					name="category_desc"
					cols="30"
					rows = "10">
				</textarea>

			</div>

			@if($errors->has('category_desc'))
			<div class="alert alert-danger">
				<small class="mb-0">Category Description is Required</small>
			</div>
			@endif




			<button type="submit" class="btn btn-primary btn-block">Add category</button>


		</form>

	</div> <!-- end of column add category -->


</div> <!-- end of row -->		

</div> <!-- end of container -->


@endsection

resources/views/assets/edit.blade.php
@extends('layouts.app')

@section('content')

<div class="container">
	<div class="row">
		<div class="col-12 cold-md-8 mx-auto">
			<h3 class="text-center">
				Edit your Asset
			</h3>
			<hr>

			@if(Session::has('update_failed'))
			<div class="alert alert-warning">
				{{ Session::get ('update_failed') }}
			</div>
			@elseif(Session::has('update_success'))
			<div class="alert alert-success">
				{{ Session::get ('update_success') }}
			</div>
			@endif

			<form action="{{ route ('assets.update', ['asset' => $asset->id]) }}" method="POST" enctype="multipart/form-data">

				@csrf
				@method('PUT')

				<div class="form-group">
					<label class="form-control" for="name">
						Asset name:
					</label>
					<input value="{{ $asset->name }}" id="name" type="text" name="name" class="form-control">

				</div> <!-- end of name input -->

				@if($errors->has('name'))
				<div class="alert alert-danger">
					<small class="mb-0">Product name Required</small>
				</div>
				@endif

				<div class="form-group">
					<label for="serial_number" class="form-control">
						Serial number:
					</label>
					<input value="{{$asset->serial_number}}" type="text" name="serial_number" id="serial_number" class="form-control">

				</div> <!-- end of serial_number -->

				@if($errors->has('serial_number'))
				<div class="alert alert-danger">
					<small class="mb-0">Serial number Required</small>
				</div>
				@endif

				<div class="form-group">
					<label for="category">
						Asset category
					</label>

					<select class="form-control" id="category" name="category">
						@foreach($categories as $category)
						<option value="{{ $category->id }}">
							{{ $category->name }}
						</option>
						@endforeach
						
					</select>

				</div> <!-- end of category -->

				@if($errors->has('category'))
				<div class="alert alert-danger">
					<small class="mb-0">Product category Required</small>
				</div>
				@endif

				<div class="form-group">
					<label for="quantity">
						Quantity:
					</label>
					<input value="{{$asset->quantity}}" type="number" name="quantity" id="quantity" class="form-control" min="1">

				</div> {{-- end of quantity input --}}

				@if($errors->has('quantity'))
				<div class="alert alert-danger">
					<small class="mb-0">Quantity is Required</small>

				</div> 
				@endif

				<div class="form-group">
					<label for="image">
						Product image:
					</label>
					<input type="file" name="image" id="image" class="form-control">		

				</div> <!-- end of image input -->

{{-- 				@if($errors->has('image'))
				<div class="alert alert-danger">
					<small class="mb-0">Product image Required Check if images is not greater that 2.00mb</small>
				</div>
				@endif --}}

				<div class="form-group">
					<label for="description">
						Product description
					</label>
					<textarea
					id="description"
					class="form-control"
					name="description"
					cols="30"
					rows = "10">
					{{$asset->description}}
				</textarea>

			</div> <!-- end of description input -->

			@if($errors->has('description'))
			<div class="alert alert-danger">
				<small class="mb-0">Product description Required</small>
			</div>
			@endif

			<button class="btn btn-primary btn-block">
				Edit asset
			</button>




		</form> {{-- end of from --}}



	</div> {{-- end of col --}}


</div> {{-- end of row --}}


</div> {{-- end of caontainer --}}

@endsection

resources/views/assets/index.blade.php
@extends('layouts.app')


@section('content')

<div class="container">
	<div class="row">
		<div class="col-12">
			<div class="jumbotron">
				<h1 class="text-center">
					Choose your equipment!!!
				</h1>

			</div> {{-- end of jumbotron --}}

		</div>{{-- end of column --}}	

	</div> {{-- end of row upper--}}

	<div class="row">
		<div class="col-12 col-md-12 mx-auto">
			<div class="row">
				@foreach($assets as $asset)
				<div class="col-12 col-md-3 mx-auto">
					{{-- start of card --}}
					<div class="card">
						<img src="{{ url('/public/' . $asset->image) }}" class="card-img-top card-image mx-auto mt-1 img-fluid img-thumbnail" 
						alt="Responsive image">

						<div class="card-body">
							<h4 class="card-title">
								{{$asset->name}}
							</h4>

							<p class="card-text">
								{{$asset->description}}
							</p>

							<p class="card-text">
								{{$asset->quantity}}
							</p>			

						</div> {{-- end of card-body --}}			
						<div class="card-foot">
							@can('isAdmin')
							<a href="{{ route ('assets.edit', ['asset' => $asset->id] ) }}" class="btn btn-success my-1 btn-sm rounded btn-block">Edit Asset</a>

							<form action="{{ route ('assets.destroy', ['asset' => $asset->id]) }}" method="POST">
								@csrf
								@method('DELETE')
								<button class="btn btn-danger btn-sm rounded btn-block">Delete Asset</button>
							</form>
							@endcannot			

						</div> {{-- end of card-foot --}}

					</div> {{-- end of card --}}
				</div>
				@endforeach

			</div>

		</div> {{-- end of column --}}		

	</div> {{-- end of lower row --}}

</div> {{-- end of caontainer --}}


@endsection

resources/views/assets/show.blade.php
@extends('layouts.app')


@section('comtent')

<div class="container">
	<div class="row">
		<div class="col-12 cold-md-8 mx-auto text-center">
			{{-- @if($asset) --}}

			<h3 class="text-center">
				Welcome to our Assets
			</h3>
			<hr>

			<div class="card">
				<img src="">

				<div class="card-body">
					<h2 class="card-title">
						SAMPLE
					</h2>
					<p class="card-text">
						SAMPLE2
					</p>
					<p class="card-text">
						SAMPLE3
					</p>
				</div> {{-- end of card body--}}

				<div class="card-foot">
					<button class="btn btn-success bt-block my-1 rouded">Request</button>
				</div> {{-- end of card-foot --}}


			</div> {{-- end of card --}}
			{{-- @endif --}}
		</div>

	</div> {{-- end of row --}}


</div> {{-- end of caontainer --}}


@endsection